sudo: false
language: java
jdk:
  - oraclejdk7
after_success:
  - mvn cobertura:cobertura coveralls:report -DrepoToken=Qi9xzH9W4PItEcK58EmWNpvQm8eanrlp5
after_script: mvn test 
notifications:
  recipients:
    - DL-PP-JAVA-SDK@ebay.com
  on_success: change
  